version: "3.3"
services:
    mysql:
        image: mysql:8.0
        ports:
          - target: 3306
            published: 3306
            mode: host

        environment:
            MYSQL_DATABASE: myDb
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - mysql:/var/lib/mysql
        networks:
            - dev

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - mysql:db
        ports:
            - target: 80
              published: 8080
              mode: host

        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
            PMA_HOST: mysql

        networks:
            - dev


networks:
  dev:
    external: true

volumes:
    mysql:
