name: Publish Docker image
on:
  push:
    branches: [ main ]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Prepare
        run: |
          export MYSQL_HOST=${{ secrets.MYSQL_HOST }}
          export MYSQL_USER=${{ secrets.MYSQL_USER }}
          export MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
          export MYSQL_PORT=${{ secrets.MYSQL_PORT }}
          echo $MYSQL_PORT

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: machinedockercyc/lottery_crawler:latest

  deploy:
    name: deploy images
    runs-on: self-hosted
    steps:
      - name: pull machinedockercyc images
        run: |
          pwd